[package]
name = "rustyblockchain"
version = "0.1.0" 
authors = ["Daniel Westheide <daniel.westheide@innoq.com>"]

[dependencies]
crypto-hash = "0.3.1"
serde = "1.0.66"
serde_derive = "1.0.66"
serde_json = "1.0.21"
rayon = "1.0.1"
histogram = "0.6.9"
